services:
  api:
    build:
      context: .
      dockerfile: ./ops/docker/app/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}              # DBのホスト名
      DB_PORT: ${DB_PORT}              # DBのポート番号
      DB_USER: ${DB_USER}              # DBユーザー名
      DB_PASSWORD: ${DB_PASSWORD}      # DBユーザーパスワード
      DB_NAME: ${DB_NAME}              # 使用するデータベース名
      ROOTPASS: ${ROOTPASS}              # DBのルートパスワード
      DATABASE_URL: ${DATABASE_URL}      # supabaseのdatabaseのURL
      SERVER_PORT: ${SERVER_PORT}        # サーバーポート
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}  # Mailgunのドメイン
      MAILGUN_PRIVATE_API_KEY: ${MAILGUN_PRIVATE_API_KEY} # MailgunのAPIキー
      SENDER_EMAIL: ${SENDER_EMAIL}        # 送信者のメールアドレス
      RECIPIENT_EMAIL: ${RECIPIENT_EMAIL}      # 受信者のメールアドレス
      JWT_SECRET: ${JWT_SECRET}          # JWTのシークレットキー
    ports:
      - "8080:8080"                    # APIのポート
    working_dir: /app                  # 作業ディレクトリ
    tty: true                          # TTYを有効にする
    restart: always
    networks:
      - app-network

volumes:
  db_data:
    driver: local                      # ローカルボリュームの使用

networks:
  app-network:
    driver: bridge                     # ブリッジネットワークの使用
